backend:
  name: git-gateway
  branch: master

media_folder: "static/img"
public_folder: "/img"

collections:

  - name: "about"
    label: "About"
    folder: "src/content/about"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      - {label: "Path", name: "path", widget: "hidden", default: "/about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "avatar", widget: "image"}

  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Services"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
      - {label: "Path", name: "path", widget: "hidden", default: "/services"}
      - name: "servicesList"
        label: "Services"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}

  - name: "productCategories"
    label: "Product Categories"
    folder: "src/content/product-categories"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-category"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}


  - name: "products"
    label: "Products"
    folder: "src/content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Category"
        name: category
        widget: relation
        collection: productCategories
        searchFields: [name]
        valueField: name
