backend:
  name: git-gateway
  branch: master

media_folder: "static/img"
public_folder: "/img"

collections:

  - name: "about"
    label: "About"
    folder: "src/content/about"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      - {label: "Path", name: "path", widget: "hidden", default: "/about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
#      - {label: "Image", name: "avatar", widget: "image"}

# WIP
#  - name: "labGuides"
#    label: "Lab How-To Guides"
#    folder: "src/content/lab-guides"
#    create: false
#    delete: false
#    slug: "{{slug}}"
#    fields:
#      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "lab-guides-page"}
#      - {label: "Path", name: "path", widget: "hidden", default: "/lab-guides"}
#      - {label: "Title", name: "title", widget: "string", default: "How to do labs at home"}
#      - {label: "Lab How-To Guides Section", name: "body", widget: "markdown"}
#
#  - name: "labResources"
#    label: "About Labs"
#    folder: "src/content/lab-resources"
#    create: false
#    delete: false
#    slug: "{{slug}}"
#    fields:
#      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "lab-resources-page"}
#      - {label: "Path", name: "path", widget: "hidden", default: "/lab-resources"}
#      - {label: "Title", name: "title", widget: "string", default: "How to do labs at home"}
#      - {label: "Lab How-To's Section", name: "body", widget: "markdown"}

  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: false
    delete: false
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
      - {label: "Path", name: "path", widget: "hidden", default: "/services"}
      - {label: "Title", name: "title", widget: "string", default: "Services"}
      - {label: "Services Section", name: "body", widget: "markdown"}

  - name: "productCategories"
    label: "Product Categories"
    folder: "src/content/product-categories"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-category"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}

  - name: "products"
    label: "Products"
    folder: "src/content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Category"
        name: category
        widget: relation
        collection: productCategories
        searchFields: [name]
        valueField: name

  - name: "labs"
    label: "Labs"
    folder: "src/content/labs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "lab"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
